In [5]:
import numpy as np

numpy.sort(a, axis=-1, kind='quicksort', order=None)

a : array_like

Array to be sorted.

axis : int or None, optional

Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

kind : {‘quicksort’, ‘mergesort’, ‘heapsort’}, optional

Sorting algorithm. Default is ‘quicksort’.

order : str or list of str, optional

When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. 
A single field can be specified as a string, and not all fields need be specified,
but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [6]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

In [3]:
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]

In [7]:
a = np.array(values, dtype=dtype)

In [11]:
np.sort(a, order='height')

array([(b'Galahad',  1.7, 38), (b'Arthur',  1.8, 41),
       (b'Lancelot',  1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [13]:
np.sort(a, order=['age', 'height'])  

array([(b'Galahad',  1.7, 38), (b'Lancelot',  1.9, 38),
       (b'Arthur',  1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

lexsort 多列排序

numpy.lexsort(keys, axis=-1)

In [15]:
a = [1,5,1,4,3,4,4] # First column

In [16]:
b = [9,4,0,4,0,2,1] # Second column

In [19]:
ind = np.lexsort((b,a)) # Sort by a, then by b

In [20]:
ind

array([2, 0, 4, 6, 5, 3, 1])

In [18]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

argmax:最最大数的index

argmin:最小的数的index

In [26]:
a = np.arange(6).reshape(2,3)

In [27]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.argmax(a)

5

In [24]:
np.argmax(a, axis=0) # axis=0 列

array([1, 1, 1])

In [25]:
np.argmax(a, axis=1) # axis=1 行

array([2, 2])

argwhere:找index位置

In [30]:
x = np.arange(6).reshape(2,3)

In [32]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

where

In [35]:
x = np.arange(9.).reshape(3, 3)

In [36]:
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [42]:
np.where( x >2 )

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [38]:
np.where( x > 5 )

(array([2, 2, 2]), array([0, 1, 2]))

In [39]:
np.where(x < 5, x, -1)   

array([[ 0.,  1.,  2.],
       [ 3.,  4., -1.],
       [-1., -1., -1.]])

In [44]:
goodvalues = [3, 4, 7]

In [45]:
ix = np.isin(x, goodvalues)

In [46]:
ix

array([[False, False, False],
       [ True,  True, False],
       [False,  True, False]], dtype=bool)

In [48]:
np.where(ix,x,-1)

array([[-1., -1., -1.],
       [ 3.,  4., -1.],
       [-1.,  7., -1.]])